language: python
dist: bionic
os:
    - linux
python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "3.8"
addons:
    apt_packages:
        - gfortran
        - gcc
env:
    - INSTALL_EXTRA=1
    - INSTALL_EXTRA=2 CDF_LIB=$HOME/lib
before_install:
    - pip install -r requirements.txt
    - bash requirements.extra $INSTALL_EXTRA
install:
    - "python setup.py install"
script:
    - "coverage run --source=ocbpy setup.py test"
after_success: coveralls
