language: python
os:
    - linux
dist: bionic
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
services: xvfb
addons:
    apt_packages:
        - gfortran
        - gcc
env:
    - INSTALL_EXTRA=1
    - INSTALL_EXTRA=2 CDF_LIB=$HOME/lib
before_install:
    - pip install -r requirements.txt
    - bash requirements.extra $INSTALL_EXTRA
    - pip install pytest
    - pip install pytest-cov
install:
    - "python setup.py install"
before_script:
  # set up display screen
  - export DISPLAY=:99.0
  - if [[ $TRAVIS_PYTHON_VERSION < "3.0" ]]; then
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
script:
    - pytest -vs --cov=ocbpy/
after_success: coveralls
